name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '16'
- run: npm install
- run: npm test
